const crearDatos = async (Albumes) => {

    await Albumes.truncate();
    await Albumes.bulkCreate([
        {artista:'A-HA', titulo: 'Memorial Beach', genero:'Rock', soporte:'Vinilo', precio:'1900'},
        {artista:'AC/DC', titulo: 'Cast In Steel', genero:'Rock', soporte:'Vinilo', precio:'800'},
        {artista:'AC/DC', titulo: 'Who Made Who', genero:'Rock', soporte:'CD', precio:'2900'},
        {artista:'Arctic Monkeys', titulo: 'Fly On The Wall', genero:'Rock', soporte:'Vinilo', precio:'500'},
        {artista:'Badu Erykah', titulo: 'Whatever People Say That Im', genero:'Rock', soporte:'Vinilo', precio:'300'},
        {artista:'Badu Erykah', titulo: 'Mama´s Gun', genero:'Rock', soporte:'Cassette', precio:'900'},
        {artista:'Bjork', titulo: 'Baduizm', genero:'Rock', soporte:'CD', precio:'900'},
        {artista:'Bjork', titulo: 'Selma Songs', genero:'Rock', soporte:'CD', precio:'600'},
        {artista:'Chemical Brothers', titulo: 'Biophilia', genero:'Rock', soporte:'Cassette', precio:'1900'},
        {artista:'Chemical Brothers', titulo: 'We Are The Night', genero:'Electronica', soporte:'CD', precio:'1700'},
        {artista:'Chet Baker', titulo: 'Dig Your Own Hole', genero:'Electronica', soporte:'CD', precio:'2900'},
        {artista:'Chet Baker', titulo: 'Complete Recordings', genero:'Jazz', soporte:'Vinilo', precio:'1700'},
        {artista:'Daft Punk', titulo: 'Chet Baker Sings', genero:'Jazz', soporte:'CD', precio:'1900'},
        {artista:'Daft Punk', titulo: 'The Many Faces Of - 3 CDs', genero:'Electronica', soporte:'CD', precio:'500'},
        {artista:'Davis Miles', titulo: 'Random Access Memories', genero:'Electronica', soporte:'CD', precio:'900'},
        {artista:'Davis Miles', titulo: 'Walkin', genero:'Jazz', soporte:'CD', precio:'1500'},
        {artista:'Divididos', titulo: 'In A Silent Way', genero:'Jazz', soporte:'Vinilo', precio:'1500'},
        {artista:'Divididos', titulo: 'Divididos', genero:'Nacional', soporte:'Vinilo', precio:'900'},
        {artista:'El Mató a un Policía Motorizado', titulo: 'Otro Le Travaladna', genero:'Nacional', soporte:'CD', precio:'1000'},
        {artista:'El Mató a un Policía Motorizado', titulo: 'Un Millón de Euros', genero:'Nacional', soporte:'Vinilo', precio:'400'},
        {artista:'El Mató a un Policía Motorizado', titulo: 'Navidad de Reserva', genero:'Nacional', soporte:'Vinilo', precio:'700'},
        {artista:'Foo Fighters', titulo: 'El Mató a un Policía Motorizado', genero:'Nacional', soporte:'Cassette', precio:'1500'},
        {artista:'Gorillaz', titulo: 'There Is Nothing Left To Lose', genero:'Rock', soporte:'CD', precio:'900'},
        {artista:'Gorillaz', titulo: 'The Fall', genero:'Rock', soporte:'CD', precio:'1000'},
        {artista:'Jimenez Carlitos La Mona', titulo: 'The Now Now', genero:'Rock', soporte:'Cassette', precio:'500'},
        {artista:'Jimenez Carlitos La Mona', titulo: 'Cuarteto es la Mona', genero:'Cuarteto', soporte:'CD', precio:'2500'},
        {artista:'Jimenez Carlitos La Mona', titulo: 'El Agite', genero:'Cuarteto', soporte:'CD', precio:'1200'},
        {artista:'Jimenez Carlitos La Mona', titulo: 'El Vicio de la Mona', genero:'Cuarteto', soporte:'Vinilo', precio:'900'},
        {artista:'Jovenes Pordioseros', titulo: 'Selección Privada 72', genero:'Cuarteto', soporte:'CD', precio:'1200'},
        {artista:'Jovenes Pordioseros', titulo: 'Vicio', genero:'Nacional', soporte:'CD', precio:'1900'},
        {artista:'Jovenes Pordioseros', titulo: 'Sangre', genero:'Nacional', soporte:'CD', precio:'800'},
        {artista:'Motörhead', titulo: 'Probame', genero:'Nacional', soporte:'CD', precio:'500'},
        {artista:'Mötorhead', titulo: 'Bastards', genero:'Metal', soporte:'Vinilo', precio:'500'},
        {artista:'Mötorhead', titulo: 'Welcome to the Bear Trap', genero:'Metal', soporte:'Vinilo', precio:'1500'},
        {artista:'New Order', titulo: 'Live at Brixton', genero:'Metal', soporte:'CD', precio:'2500'},
        {artista:'New Order', titulo: 'Waiting For The Sirens Call', genero:'Electronica', soporte:'Vinilo', precio:'3000'},
        {artista:'New Order', titulo: 'Brotherhood', genero:'Electronica', soporte:'Vinilo', precio:'3500'},
        {artista:'Nirvana', titulo: 'Movement', genero:'Electronica', soporte:'Cassette', precio:'3500'},
        {artista:'Nirvana', titulo: 'Nevermind', genero:'Rock', soporte:'CD', precio:'3500'},
        {artista:'Pandolfo Palo', titulo: 'In Bloom Collection', genero:'Rock', soporte:'CD', precio:'3900'},
        {artista:'Pandolfo Palo', titulo: 'Antojo', genero:'Nacional', soporte:'Cassette', precio:'3500'},
        {artista:'Patricio Rey Y Sus Redonditos De Ricota', titulo: 'A traves de los sueños', genero:'Nacional', soporte:'CD', precio:'2900'},
        {artista:'Patricio Rey Y Sus Redonditos De Ricota', titulo: 'Ultimo Bondi A Finisterre', genero:'Nacional', soporte:'CD', precio:'3300'},
        {artista:'Pearl Jam', titulo: 'Momo Sampler', genero:'Nacional', soporte:'Vinilo', precio:'1900'},
        {artista:'Pearl Jam', titulo: 'Binaural', genero:'Rock', soporte:'CD', precio:'200'},
        {artista:'Pink Floyd', titulo: 'Riot Act', genero:'Rock', soporte:'Vinilo', precio:'400'},
        {artista:'Pixies', titulo: 'Obscured by Clouds', genero:'Rock', soporte:'Vinilo', precio:'400'},
        {artista:'Primus', titulo: 'Trompe Le Monde', genero:'Rock', soporte:'CD', precio:'500'},
        {artista:'Rage Against The Machine', titulo: 'Green Naugahyde', genero:'Rock', soporte:'Vinilo', precio:'700'},
        {artista:'Ramones The', titulo: 'The Battle of L.A', genero:'Rock', soporte:'Vinilo', precio:'500'},
        {artista:'Ramones The', titulo: 'Mondo Bizarro', genero:'Rock', soporte:'Cassette', precio:'3900'},
        {artista:'Soda Stereo', titulo: 'Pleasent Dreams', genero:'Rock', soporte:'CD', precio:'1800'},
        {artista:'Soda Stereo', titulo: 'Canción Animal', genero:'Nacional', soporte:'CD', precio:'1900'},
        {artista:'ZZ Top', titulo: 'Sueño Stereo', genero:'Nacional', soporte:'Cassette', precio:'900'},
        {artista:'ZZ Top', titulo: 'Eliminator', genero:'Rock', soporte:'CD', precio:'2900'},
        {artista:'ZZ Top', titulo: 'Tejas', genero:'Rock', soporte:'CD', precio:'2900'},
        {artista:'ZZ Top', titulo: 'Fandango', genero:'Rock', soporte:'Vinilo', precio:'2900'},
        
    ]);
}

module.exports = crearDatos;
